//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumPosts
    {
        public int Id { get; set; }
        public int ForumTopicId { get; set; }
        public int UserId { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public string Title { get; set; }
    
        public virtual User User { get; set; }
        public virtual ForumTopic ForumTopic { get; set; }
    }
}
