//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumTopic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForumTopic()
        {
            this.ForumPosts = new HashSet<ForumPosts>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ForumCategoriesId { get; set; }
        public System.DateTime Date { get; set; }
        public string Subject { get; set; }
    
        public virtual ForumCategories ForumCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumPosts> ForumPosts { get; set; }
        public virtual User User { get; set; }
    }
}
