//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanger.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HangerDatabase : DbContext
    {
        public HangerDatabase()
            : base("name=HangerDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad> Ad { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Condition> Condition { get; set; }
        public virtual DbSet<ForumCategories> ForumCategories { get; set; }
        public virtual DbSet<ForumPosts> ForumPosts { get; set; }
        public virtual DbSet<ForumTopic> ForumTopic { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<PhotoSite> PhotoSite { get; set; }
        public virtual DbSet<Size> Size { get; set; }
        public virtual DbSet<Subcategory> Subcategory { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserPhoto> UserPhoto { get; set; }
        public virtual DbSet<SubSubcategory> SubSubcategory { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Favourite> Favourite { get; set; }
        public virtual DbSet<UserProfil> UserProfil { get; set; }
    }
}
